[package]
name = "day-05"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
itertools = { workspace = true }
nom = { workspace = true }
nom-supreme = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }
dhat = { workspace = true }
rayon = { workspace = true }
indicatif = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
rstest = "0.18.2"

[[bench]]
name = "day-05"
path = "benches/benchmarks.rs"
harness = false

[features]
dhat-heap = []