[workspace]
members = [
    "common",
    "day-*",
    "day-14",
    "day-15",
    "day-16",
    "day-19",
]
default-members = ["day-*"]
resolver = "3"

[workspace.dependencies]
bitvec = "1.0.1"
bytes = "1.5.0"
cached = "0.53.1"
ctor = "0.6.2"
dhat = "0.3.2"
divan = "0.1.4"
glam = "0.30"
itertools = "0.14.0"
log = "0.4.28"
nom = "8.0.0"
nom-supreme = "0.8.0"
nom_locate = "5.0.0"
once_cell = "1.19.0"
pathfinding = "4.14"
petgraph = "0.6.4"
rayon = "1.8.0"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
thiserror = "1.0.50"
tracing = "0.1.43"
tracing-tracy = "0.10.4"
tracy-client = "0.16.4"
tracy-client-sys = "0.22.0"

[workspace.dependencies.test-log]
version = "0.2.13"
features = ["trace"]
default-features = false

[workspace.dependencies.tracing-subscriber]
version = "0.3.18"
features = [
    "fmt",
    "env-filter",
]
