# Use `just work day-01 part1` to work on the specific binary for a specific day's problems

work day part:
    cargo watch -x "check -p {{day}}" -s "just test {{part}} -p {{day}}" -s "just lint {{day}}"

lint day:
    cargo clippy -p {{day}}

test part +FLAGS='-p day-01':
    cargo nextest run {{FLAGS}} {{part}}

bench-all:
    cargo bench -q > benchmarks.txt

bench day part:
    cargo bench --bench {{day}}-bench {{part}} >> {{day}}.bench.txt

# create the directory for a new day's puzzle and fetch the input
create day:
    cargo generate --path ./daily-template --name {{day}}
